### ISSUE TITLE
Server platform?

### ISSUE THREAD

**Issue by PBrunot** [fablab-bergamo/rfid-database-interface#1]
What would be your opinion regarding implementation of the server on another ESP32?

Personally I can see benefits:
- network robustness (boards could connect in dedicated mesh wifi, like ESPnow, allowing better range/stability in theory)
- better availability (system can work without Internet access, as the server will be on)
- integration with FabManager through REST/API is still doable (ESP32 supports Wifi + ESPNow)
- no hosting costs

Disadvantages:
- Even if ESP32 can host simple website, admin website will not be as friendly as can be a dedicated website could be
- Website development on ESP32 will be more cumbersome
- State (users, history) will need to be backup'd / uploaded somewhere

Most of the libraries are available (http client, SQLite, ESPNow, local webserver) so I don't see any real blocker.

Also, it looks reasonably "challenging" to implement on an embedded platform - what's why it sounds cool to me.

**Comment by valerionew** [comment]
Honestly I don't see this as a very good solution. I think an in-between solution would be better for this, such as a Raspberry PI or a similar platform locally. We even have a local server in the lab for this. A Python application could be run both on an RPI and on a bigger server if needed. Moreover, Python is much easier to debug with respect to an embedded solution.

While I see your points about network and availability, these still apply to the local server solution.

At last: the network infrastructure we have, allows for an easy and quick deployment of a dedicated WiFi network.

**Comment by PBrunot** [comment]
Thanks for your comment.
I agree... especially maintenability.
Probably a raspberry pi is the best compromise to have a reliable local
infrastructure with minimal effort (I was not aware there was one in the
Lab!)
